import { RunwareServer } from "@runware/sdk-js";
import type { Slide, TextOverlay } from "../types/index.js";
import { v4 as uuidv4 } from "uuid";

let runwareInstance: InstanceType<typeof RunwareServer> | null = null;

function getRunware(): InstanceType<typeof RunwareServer> {
  if (!runwareInstance) {
    runwareInstance = new RunwareServer({
      apiKey: process.env.RUNWARE_API_KEY!,
    });
  }
  return runwareInstance;
}

/**
 * Generate a slide image.
 *
 * When `referenceImage` (base64 data URI) is supplied the request is sent to
 * GPT Image 1.5 (`openai:4@1`), which extracts the subject from the reference
 * and places it into a brand-new scene described entirely by `prompt`.
 * The image is cropped to portrait 1024×1536 (the closest supported 2:3 ratio).
 *
 * Without a reference the existing fast model (`runware:101@1`) is used at the
 * original 576×1024 portrait size.
 */
export async function generateSlideImage(
  prompt: string,
  referenceImage?: string
): Promise<string> {
  const runware = getRunware();

  let requestParams: Record<string, any>;

  if (referenceImage) {
    // Image-to-image: GPT Image 1.5 understands the subject in the reference
    // and generates a brand-new composition driven by the text prompt.
    requestParams = {
      positivePrompt: prompt,
      model: process.env.RUNWARE_IMAGE_MODEL || "openai:4@1",
      width: 1024,
      height: 1536,
      numberResults: 1,
      // Pass the product photo as a reference so the model learns what object
      // to feature; the text prompt alone defines the new context/scene.
      referenceImages: [referenceImage],
    };
  } else {
    // Text-to-image: original fast model, no reference image.
    requestParams = {
      positivePrompt: prompt,
      model: "runware:101@1",
      width: 576,
      height: 1024,
      numberResults: 1,
      negativePrompt:
        "text, words, letters, watermark, logo, blurry, low quality, distorted",
    };
  }

  const images = await runware.requestImages(requestParams as any);

  if (!images || images.length === 0) {
    throw new Error("No image generated by Runware");
  }

  return (images[0] as any).imageURL || (images[0] as any).imageUrl;
}

export async function generateSlide(
  prompt: string,
  textOverlays: TextOverlay[],
  referenceImage?: string
): Promise<Slide> {
  const imageUrl = await generateSlideImage(prompt, referenceImage);

  return {
    id: uuidv4(),
    imageUrl,
    imagePrompt: prompt,
    textOverlays,
  };
}
