import { RunwareServer } from "@runware/sdk-js";
import type { Slide, TextOverlay } from "../types/index.js";
import { v4 as uuidv4 } from "uuid";

let runwareInstance: InstanceType<typeof RunwareServer> | null = null;

function getRunware(): InstanceType<typeof RunwareServer> {
  if (!runwareInstance) {
    runwareInstance = new RunwareServer({
      apiKey: process.env.RUNWARE_API_KEY!,
    });
  }
  return runwareInstance;
}

export async function generateSlideImage(prompt: string): Promise<string> {
  const runware = getRunware();

  const images = await runware.requestImages({
    positivePrompt: prompt,
    model: "runware:101@1",
    width: 576,
    height: 1024,
    numberResults: 1,
    negativePrompt:
      "text, words, letters, watermark, logo, blurry, low quality, distorted",
  });

  if (!images || images.length === 0) {
    throw new Error("No image generated by Runware");
  }

  return (images[0] as any).imageURL || (images[0] as any).imageUrl;
}

export async function generateSlide(
  prompt: string,
  textOverlays: TextOverlay[]
): Promise<Slide> {
  const imageUrl = await generateSlideImage(prompt);

  return {
    id: uuidv4(),
    imageUrl,
    imagePrompt: prompt,
    textOverlays,
  };
}
